name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build (Python ${{ matrix.python-version }},Poetry ${{matrix.poetry-version}} Os ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
        poetry-version: ["1.2.2","1.6.1", "1.7.1"]
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      # Install dependencies using Poetry 
      - name: Install dependencies
        run: poetry install

      # Code quality checks
      - name: Run code quality checks
        run: make check

      # Tests with coverage
      - name: Run tests with coverage
        run: make test-cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
         token: ${{ secrets.CODECOV_TOKEN }}
         slug: bharathram444/fluttrfly
         fail_ci_if_error: true
         verbose: true

